# Generated by Django 2.2 on 2019-06-20 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'blog categories',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('image', models.FileField(null=True, upload_to='static/upload/')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('N', 'Normal')], max_length=1)),
                ('other', models.TextField(max_length=250)),
                ('designation', modelcluster.fields.ParentalManyToManyField(blank=True, to='details.Choice')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Page',
                'verbose_name_plural': 'Profile Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
