# Generated by Django 2.2 on 2019-06-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileindexpage',
            old_name='profiletitle',
            new_name='profilesubtitle',
        ),
    ]
