# Generated by Django 2.2 on 2019-06-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/upload/'),
        ),
    ]
