# Generated by Django 2.2 on 2019-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('details', '0003_profilepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(null=True, upload_to='static/upload/')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('N', 'Normal')], max_length=1)),
                ('designation', models.CharField(choices=[('P', 'Python'), ('NJ', 'Node.js'), ('D', 'Designer'), ('AN', 'Android'), ('I', 'IOS')], max_length=25)),
                ('other', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ProfileIndexPage',
        ),
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
