# Generated by Django 2.2 on 2019-06-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20190618_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='clip',
            new_name='image',
        ),
    ]
