# Generated by Django 2.2 on 2019-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20190618_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='designation',
            field=models.CharField(max_length=25),
        ),
    ]
