# Generated by Django 2.2 on 2019-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_auto_20190618_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], max_length=1),
        ),
    ]
