# Generated by Django 2.2 on 2019-06-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_auto_20190618_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'Profile Page', 'verbose_name_plural': 'Profile Pages'},
        ),
    ]
